controller_names:
  - left_arm_controller
  - right_arm_controller
  - left_gripper_controller
  - right_gripper_controller

left_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_fr3_joint1
    - left_fr3_joint2
    - left_fr3_joint3
    - left_fr3_joint4
    - left_fr3_joint5
    - left_fr3_joint6
    - left_fr3_joint7

right_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - right_fr3_joint1
    - right_fr3_joint2
    - right_fr3_joint3
    - right_fr3_joint4
    - right_fr3_joint5
    - right_fr3_joint6
    - right_fr3_joint7

# Gripper (hand) controllers
left_gripper_controller:
  action_ns: gripper_action
  type: GripperCommand
  default: false
  joints:
    - left_fr3_finger_joint1
    - left_fr3_finger_joint2

right_gripper_controller:
  action_ns: gripper_action
  type: GripperCommand
  default: false
  joints:
    - right_fr3_finger_joint1
    - right_fr3_finger_joint2