services:
  franka:
    image: eric.franka_ws:latest
    container_name: franka_ws
    network_mode: "host"
    ipc: "host"
    privileged: true
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ../:/workspaces/franka_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/mj/.Xauthority:rw
    working_dir: /workspaces/franka_ws
    stdin_open: true
    tty: true
    entrypoint: /workspaces/franka_ws/docker/entrypoint.sh
    command: bash
